#!/bin/bash

set -e

echo "\033[36;1mRunning tests on debug with default features:\033[0m"
cargo test && (cd test_dymod && cargo test)

echo "\033[36;1mRunning tests on release with default features:\033[0m"
cargo test --release && (cd test_dymod && cargo test --release)

echo "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --check && (cd test_dymod && cargo fmt -- --check)

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo clippy -- -D clippy::all && (cd test_dymod && cargo clippy -- -D clippy::all)
