#!/bin/bash

set -e

echo -e "\033[36;1mRunning debug tests:\033[0m"
cargo test && (cd test_dymod && cargo test)

echo -e "\033[36;1mRunning debug/force-static tests:\033[0m"
cargo test --features force-static && (cd test_dymod && cargo test --features force-static)

echo -e "\033[36;1mRunning debug/force-dynamic tests:\033[0m"
cargo test --features force-dynamic && (cd test_dymod && cargo test --features force-dynamic)

echo -e "\033[36;1mRunning debug/auto-reload tests:\033[0m"
cargo test --features auto-reload && (cd test_dymod && cargo test --features auto-reload)

echo -e "\033[36;1mRunning release tests:\033[0m"
cargo test --release && (cd test_dymod && cargo test --release)

echo -e "\033[36;1mRunning release/force-static tests:\033[0m"
cargo test --release --features force-static && (cd test_dymod && cargo test --release --features force-static)

echo -e "\033[36;1mRunning release/force-dynamic tests:\033[0m"
cargo test --release --features force-dynamic && (cd test_dymod && cargo test --release --features force-dynamic)

echo -e "\033[36;1mRunning release/auto-reload tests:\033[0m"
cargo test --release --features auto-reload && (cd test_dymod && cargo test --release --features auto-reload)

echo "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --check && (cd test_dymod && cargo fmt -- --check)

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo clippy -- -D clippy::all && (cd test_dymod && cargo clippy -- -D clippy::all)
